zanata.xml
The zanata.xml file is no longer used
=> Delete unused zanata.xml file

spec/factories/ext_management_system.rb, spec/models/manageiq/providers/nsxt/network_manager/refresher_spec.rb
There was a duplicate factory added to core [here](https://github.com/ManageIQ/manageiq/pull/20269) so we can delete this
=> Factories were added to core so not needed

app/javascript/components/cloud-networks/create-nsxt-cloud-network-form.jsx, app/javascript/components/cloud-networks/nsxt-cloud-network-form.schema.js, app/javascript/components/cloud-networks/update-nsxt-cloud-network-form.jsx, app/javascript/components/security-groups/create-nsxt-security-group-form.jsx, app/javascript/components/security-groups/nsxt-security-group-form.schema.js, app/javascript/components/security-groups/update-nsxt-security-group-form.jsx, app/javascript/components/security-policies/create-nsxt-security-policy-form.jsx, app/javascript/components/security-policies/nsxt-security-policy-form.schema.js, app/javascript/components/security-policies/update-nsxt-security-policy-form.jsx, app/javascript/components/security-policy-rules/create-nsxt-security-policy-rule-form.jsx, app/javascript/components/security-policy-rules/nsxt-security-policy-rule-form.schema.js, app/javascript/components/security-policy-rules/update-nsxt-security-policy-rule-form.jsx
https://github.com/ManageIQ/manageiq-ui-classic/issues/7277
=> Update the DDF schema to version 2

.gitignore, .travis.yml, .yamllint, LICENSE.txt, README.md, Rakefile, bin/ci/after_script, lib/manageiq/providers/nsxt/engine.rb, lib/tasks/README.md, lib/tasks_private/spec.rake, lib/tasks_private/yarn.rake, manageiq-providers-nsxt.gemspec, spec/spec_helper.rb
=> Plugin Generator Updates

app/assets/application_helper/button/any_nsxt_network_manager.rb, app/assets/application_helper/button/belongs_to_nsxt_network_manager.rb, app/helper/manageiq/providers/nsxt/toolbar_overrides/cloud_network_center.rb, app/helper/manageiq/providers/nsxt/toolbar_overrides/cloud_networks_center.rb, app/helper/manageiq/providers/nsxt/toolbar_overrides/security_group_center.rb, app/helper/manageiq/providers/nsxt/toolbar_overrides/security_groups_center.rb, app/helper/manageiq/providers/nsxt/toolbar_overrides/security_policies_center.rb, app/helper/manageiq/providers/nsxt/toolbar_overrides/security_policy_center.rb, app/helper/manageiq/providers/nsxt/toolbar_overrides/security_policy_rule_center.rb, app/helper/manageiq/providers/nsxt/toolbar_overrides/security_policy_rules_center.rb
* Changed the visibility of the New button only when a NSX-T providers is available for the user
* Changed the visibility of the Update and Delete button only when the record is part of the NSX-T Network Manager
* Some textual changes
Should help with:
https://github.com/ManageIQ/manageiq-ui-classic/issues/7465
=> Visibility of Nsxt new buttons

lib/manageiq/providers/nsxt/engine.rb
Move logger initialization and configuration into plugins
=> Move logger initialization and configuration into plugins

app/models/manageiq/providers/nsxt/inventory/parser/network_manager.rb, app/models/manageiq/providers/nsxt/network_manager/security_policy_rule.rb, app/models/manageiq/providers/nsxt/nsxt_client.rb, app/models/manageiq/providers/nsxt/nsxt_client/rest.rb, spec/models/manageiq/providers/nsxt/network_manager/refresher_spec.rb
Update of Inventory Refresh
* Added support for shared Network Services
* Fixed mapping of some Network Service Entry types
* Fixed mapping of Cloud Networks
* Added Security Groups to Cloud Subnet relations using Network Ports
* Added support for Destinations Excluded and Sources Excluded to Security Policy Rules 
Depend on:
https://github.com/ManageIQ/manageiq-schema/pull/569
https://github.com/ManageIQ/manageiq-schema/pull/570
=> Update of Inventory Refresh

systemd/manageiq-providers-nsxt_network_manager_refresh@.service
part of https://github.com/ManageIQ/manageiq-rpm_build/pull/157
using manageiq properties and still running as root (but very close to switching over to manageiq user)
=> add properties files to systemd

systemd/manageiq-providers-nsxt_network_manager_refresh@.service
=> run services as manageiq user

app/javascript/components/cloud-networks/delete-nsxt-cloud-network-form.jsx, app/javascript/components/security-groups/delete-nsxt-security-group-form.jsx, app/javascript/components/security-policies/delete-nsxt-security-policy-form.jsx, app/javascript/components/security-policy-rules/delete-nsxt-security-policy-rule-form.jsx
Issue--> https://github.com/ManageIQ/manageiq-ui-classic/issues/7979
Replaced PF react modal component with carbon modal.
@miq-bot assign @agrare 
@miq-bot add_reviewer @agrare 
@miq-bot add-label enhancement
=> Replace PF react component with carbon

app/models/manageiq/providers/nsxt/inventory/collector/target_collection.rb
=> Move add_target and references to core collector

app/models/manageiq/providers/nsxt/network_manager.rb
part of part of https://github.com/ManageIQ/manageiq/pull/21573
=> converting supported_for_create to supports :create

app/models/manageiq/providers/nsxt/inventory/persister/definitions/network_collections.rb
Required for: https://github.com/ManageIQ/manageiq/pull/21597
=> Skip STI for referenced VMs

package.json, yarn.lock
We don't need jest package as do not have js testcases in this repo.
@miq-bot assign @Fryguy 
@miq-bot add-label technical_debt
@miq-bot add_reviewer @Fryguy
=> Remove jest package

app/models/manageiq/providers/nsxt/manager_mixin.rb
Continuing to remove uneeded memoization.
@miq-bot add-label bug
@miq-bot add-label najdorf/yes?
@miq-bot assign @agrare
=> Removing Memoization

package.json, yarn.lock
Related to https://github.com/ManageIQ/manageiq-rpm_build/pull/409
=> Lock down es-abstract

package.json
=> Upgrade package to 2.0.1

package.json
[MORPHY] Upgrade ip package 2.0.1
@miq-bot add-reviewer @Fryguy
@miq-bot add-reviewer @agrare 
@miq-bot add-label security fix
@miq-bot assign @Fryguy
@miq-bot assign @agrare
=> [MORPHY] Upgrade ip package 2.0.1

yarn.lock
@GilbertCherrie Please review.
=> Update yarn.lock to latest dependencies

lib/manageiq/providers/nsxt/engine.rb
Depends indirectly on: https://github.com/ManageIQ/manageiq/pull/23509
=> Drop to_s on engine paths
